---
- name: Create /opt/devops directory on AWS nodes
  hosts: aws
  become: yes
  tasks:
    - name: Ensure /opt/devops directory exists
      ansible.builtin.file:
        path: /opt/devops
        state: directory
        mode: '0755'

